server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /sportlife/ {
        try_files $uri $uri/ /sportlife/index.html;
    }

    location / {
        return 301 /sportlife/;
    }
}
